# Generated by Django 2.0 on 2019-03-12 19:54

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20190312_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='skills',
            field=wagtail.fields.StreamField((('skills', wagtail.blocks.StructBlock((('skills', wagtail.blocks.CharBlock(classname='full title')), ('percentage', wagtail.blocks.CharBlock(classname='full title'))))),), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='skills_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
