# Generated by Django 2.0 on 2019-03-14 15:54

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_auto_20190314_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='project',
            field=wagtail.fields.StreamField((('project', wagtail.blocks.StructBlock((('name', wagtail.blocks.CharBlock(classname='full title')), ('description', wagtail.blocks.RichTextBlock()), ('excerpt', wagtail.blocks.RichTextBlock(blank=True)), ('menu_title', wagtail.blocks.CharBlock(classname='full title')), ('project_url', wagtail.blocks.URLBlock(classname='full title')), ('project_image', wagtail.images.blocks.ImageChooserBlock()), ('image_text', wagtail.blocks.CharBlock(classname='full title')), ('start_date', wagtail.blocks.CharBlock(classname='full title')), ('end_date', wagtail.blocks.CharBlock(classname='full title')), ('language', wagtail.blocks.StreamBlock((('skills', wagtail.blocks.CharBlock()),), icon='user'))))),), blank=True, null=True),
        ),
    ]
